deploy

diff --git a/.github/workflows/nodejs.yml b/.github/workflows/nodejs.yml
--- a/.github/workflows/nodejs.yml
+++ b/.github/workflows/nodejs.yml
@@ -22,11 +22,25 @@ jobs:
       id: ssh
       run: |
         set -e
-        if ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS }} sudo bash < /home/ubuntu/update.sh; then
-          echo "SSH command succeeded, sending notification to Slack"
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Github update script initiated."}' ${{ secrets.SLACK_WEBHOOK_URL }}
+        # Define the directory to list, change if needed
+        DIRECTORY_TO_LIST="/home/ubuntu"
+
+        # List the contents of the directory on the EC2 instance
+        if ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS }} "ls -a $DIRECTORY_TO_LIST"; then
+          echo "Directory listing succeeded, proceeding with the update script."
+          
+          # Execute the update script
+          if ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_DNS }} sudo bash < /home/ubuntu/update.sh; then
+            echo "SSH command succeeded, sending notification to Slack"
+            curl -X POST -H 'Content-type: application/json' --data '{"text":"Github update script initiated."}' ${{ secrets.SLACK_WEBHOOK_URL }}
+          else
+            echo "SSH command failed, sending notification to Slack"
+            curl -X POST -H 'Content-type: application/json' --data '{"text":"Github update script initiation failed!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+            exit 1
+          fi
         else
-          echo "SSH command failed, sending notification to Slack"
-          curl -X POST -H 'Content-type: application/json' --data '{"text":"Github update script initiation failed!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
+          echo "Directory listing failed, sending notification to Slack"
+          curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed to list directory contents on EC2 instance!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
           exit 1
         fi
+
